# -*- coding: utf-8 -*-
"""08 - BagOfWords.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16K9eNawK7Oli4ZnUm0r1nLcTiWRuTYW_
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 08-BagOfWords.py
# import csv
# 
# class BagOfWords:
#     def transform(self, processed_data):
#         # 1. Reading the unique words from the 'unique_words.txt' file.
#         unique_words = []  # List to hold unique words
#         word_count = {}  # Dictionary to count occurrences of words
#         with open('05 - unique words.txt', 'r') as in_file:
#             lines = in_file.readlines()  # Read all lines in the file
#             for z, line in enumerate(lines):
#                 word = line.strip()  # Remove any leading/trailing spaces
#                 print(f"Reading....{z+1} {word}")  # Display progress
#                 unique_words.append(word)  # Add the word to the unique_words list
# 
#         print(f"Unique words: {len(unique_words)}")  # Print the total number of unique words
# 
#         # 2. Writing the columns (unique words) in the output 'BagOfWords.csv' file.
#         with open('08 - BagOfWords.csv', 'w', newline='') as out_file:
#             writer = csv.writer(out_file)  # Initialize the CSV writer
#             writer.writerow(unique_words)  # Write the unique words as the header
# 
#             # 3. Creating the Bag of Words matrix.
#             for i, sentence in enumerate(processed_data):
#                 for word in sentence:
#                     word_count[word] = word_count.get(word, 0) + 1  # Count occurrences of words in the sentence
# 
#                 # Write the count of each unique word in the current sentence.
#                 row = []
#                 for unique_word in unique_words:
#                     # If the word is found in the current sentence, add its count, otherwise add 0
#                     row.append(word_count.get(unique_word, 0))
#                 writer.writerow(row)  # Write the row to the CSV file
# 
#                 word_count.clear()  # Clear the word count dictionary for the next sentence
#                 print(f"{i+1}")  # Display progress
# 
# # Example of how you might use the class (assuming processed_data is available):
# # bag_of_words = BagOfWords()
# # bag_of_words.transform(processed_data)
#

!python /content/08-BagOfWords.py